name: check_pull_request_branch_type

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  check_pr_branch_type:
    runs-on: ubuntu-latest
    outputs:
      incremental_type: ${{ steps.determine_branch_type.outputs.incremental_type }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Determine branch type
        id: determine_branch_type
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          branch_prefix=$(echo ${{ env.BRANCH_NAME }} | cut -d '/' -f1)
          echo "branch_prefix=$branch_prefix" >> $GITHUB_ENV
          if [ "$branch_prefix" == "release" ]; then
            incremental_type=MAJOR
          elif [ "$branch_prefix" == "feature" ]; then
            incremental_type=MINOR
          elif [ "$branch_prefix" == "hotfix" ]; then
            incremental_type=MINOR
          elif [ "$branch_prefix" == "patch" ]; then
            incremental_type=PATCH
          else
            incremental_type=UNKNOWN
          fi
          
          if [ "$incremental_type" == "UNKNOWN" ] ; then
            echo "needs_error_handling=true" >> $GITHUB_ENV
          else
            echo "needs_error_handling=false" >> $GITHUB_ENV
            echo "incremental_type=$incremental_type" >> $GITHUB_OUTPUT
          fi
          
      - name: Error Handling
        id: error_handling
        if: ${{ env.needs_error_handling == 'true' }}
        run: |          
          case "$branch_prefix" in
            # Exceptions for wrong branch name
            "gh-action")
              skip_gen_release=true
              ;;
            # Everything else is wrong
            *)
              skip_gen_release=false
              ;;
          esac
          
          if [ "$skip_gen_release" == "false" ] ; then
            echo "::error ::Wrong Branch Name"
            exit 1
          fi
