name: release-automation-main

on:
  workflow_call:

jobs:
  check_pr_branch_type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine branch type
        id: determine_branch_type
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          branch_prefix=$(echo ${{ env.BRANCH_NAME }} | cut -d '/' -f1)
          
          if [ "$branch_prefix" == "release" ]; then
            echo "INCREMENTAL_TYPE='MAJOR'" >> $GITHUB_ENV
            echo "IS_RELEASE_BRANCH=true" >> $GITHUB_ENV
          elif [ "$branch_prefix" == "feature" ]; then
            echo "INCREMENTAL_TYPE='MINOR'" >> $GITHUB_ENV
          elif [ "$branch_prefix" == "hotfix" ]; then
            echo "INCREMENTAL_TYPE='MINOR'" >> $GITHUB_ENV
          elif [ "$branch_prefix" == "patch" ]; then
            echo "INCREMENTAL_TYPE='PATCH'" >> $GITHUB_ENV
          else 
            case "$branch_prfix" in
              "gh-action") skip_gen_release=true ;;
              *) skip_gen_release=false ;;
            esac
            echo "SKIP_GEN_RELEASE=$skip_gen_release" >> $GITHUB_ENV
            echo "INCREMENTAL_TYPE='UNKNOWN'" >> $GITHUB_ENV
          fi

      - name: Generate Release
        if: ${{ env.INCREMENTAL_TYPE }} != 'UNKNOWN'
        uses: tmaxopensql/release-automation/.github/workflows/generate-release.yml@main
        with:
          INCREMENTAL_TYPE: ${{ env.INCREMENTAL_TYPE }}

      - name: Error Handling
        if: ${{ env.SKIP_GEN_RELEASE }} == false && ${{ env.INCREMENTAL_TYPE }} == 'UNKNOWN'
        run: echo "::error file=main.yml::Wrong Branch Name"

